=== MALTT-STIC/stic-2-xml-dtd-xslt/examples/05-advanced/web-app.dtd
<!-- Déclaration du document qui contient le nom de l'application, la description, le lien hypertextuel, les pages qui la composent, et des éléments communs à différents pages (e.g. header, navigation, etc) -->
<!ELEMENT web-app (app-info, pages, components?)>
<!-- Déclaration des info de l'application-->
<!ELEMENT app-info (app-name, app-description, app-url?)>
<!-- Nom de l'application (e.g. "EduTech Blog") -->
<!ELEMENT app-name (#PCDATA)>
<!-- Description de l'application ("e.g. "Blog qui parle des technologies de l'information") -->
<!ELEMENT app-description (#PCDATA)>
<!-- Adresse web de l'application, si déjà disponible (e.g. "http://edutechblog.unige.ch") -->
<!ELEMENT app-url (#PCDATA)>
<!-- Déclarations des différentes pages qui composent l'application -->
<!ELEMENT pages (page+)>
<!-- Pour chaque page il faut illustrer des informations générales, comme le titre, l'url et la description, ainsi que les trois "layers" MVC -->
<!ELEMENT page (page-title, page-href?, page-description, model, view, controller)>
<!-- Titre de la page (e.g. "Page d'accueil") -->
<!ELEMENT page-title (#PCDATA)>
<!-- Adresse web relatif de la page, si déjà disponible (sans l'url de l'application) (e.g. "/index.html") -->
<!ELEMENT page-href (#PCDATA)>
<!-- Description de la page (e.g. "Page d'accueil du blog avec présentation des derniers articles") -->
<!ELEMENT page-description (#PCDATA)>
<!-- Informations relatives au "layer" Model qui comprennent la logic de programmation sous-jacente et les variables mises à disposition des designers -->
<!ELEMENT model (processes?, variables?)>
<!-- La logic décrit les processus computationnels -->
<!ELEMENT processes (process*)>
<!-- Description des différents processus computationnels actifs dans la page ("e.g. "Recupérer les 10 derniers articles du blog") -->
<!ELEMENT process (process-description)>
<!-- Déscription du process -->
<!ELEMENT process-description (#PCDATA)>
<!-- Liste des variables mises à disposition des designers -->
<!ELEMENT variables (var*)>
<!-- Pour chaque variable on déclare le nom, le type de variable, et son contenu -->
<!ELEMENT var (var-name, var-type, var-content)>
<!-- Le nom de la variable indique la notation à travers laquelle les designers peuvent "imprimer sur la page" l'information issues des processus logiques (e.g. "derniersDixArticles") -->
<!ELEMENT var-name (#PCDATA)>
<!-- Le type de variable indique les actions que les designers peuvent effectuer sur la variable (e.g. "Array") -->
<!ELEMENT var-type (#PCDATA)>
<!-- Description du contenu de la variable (e.g. "Titre, Date, Auteur, Contenu, Url") -->
<!ELEMENT var-content (#PCDATA)>
<!-- Information relatives au "layer" View qui comprennent l'agencement du contenu de la page (avec un dessin optionnel) et les éléments communs à d'autres pages -->
<!ELEMENT view (layout-description, sketch?, components-list?)>
<!-- Description générale du layout de la page (e.g. "La page d'accueil présente un texte introductif sur l'objectif du blog ainsi que les 10 derniers articles") -->
<!ELEMENT layout-description (#PCDATA)>
<!-- Url d'un dessin qui représente la page -->
<!ELEMENT sketch (#PCDATA)>
<!-- Listes des noms des éléments communs à différents pages qui sont présents dans cette page (e.g. "Entête, Navigation principale, Pié-de-page") -->
<!ELEMENT components-list (component-name+)>
<!-- Informations relatives au "layer" Controller qui comprennent les comportements de l'utilisateur qui peuvent influencer les autres deux "layers" -->
<!ELEMENT controller (actions)>
<!-- Liste des interactions possibles avec la page -->
<!ELEMENT actions (action+)>
<!-- Description de l'interaction et conséquences événtuelles sur les deux autres layers (e.g. "voir les 10 prochains articles") -->
<!ELEMENT action (#PCDATA)>
<!-- Liste des éléments communs à plusieurs pages de l'application -->
<!ELEMENT components (component*)>
<!-- Un élément commun a plus au moins les mêmes informations d'une page, y compris les trois "layers" MVC -->
<!ELEMENT component (component-name, component-description, model, view, controller)>
<!-- Le nom de l'élément commun (e.g. "Menu principale" -->
<!ELEMENT component-name (#PCDATA)>
<!-- La description de l'élément commun -->
<!ELEMENT component-description (#PCDATA)>

=== MALTT-STIC/stic-2-xml-dtd-xslt/examples/05-advanced/welcome.xml
<?xml version="1.0"?>
<?xml-stylesheet href="web-app.xsl" type="text/xsl"?>
<!DOCTYPE web-app SYSTEM "web-app.dtd">
 
<web-app>
	<app-info>
		<app-name>MALTT-NOTES</app-name>
		<app-description>Application qui permet aux étudiants inscrits au Master MALTT de consulter leurs propres notes obtenues pendant le MASTER</app-description>
		<app-url>http://tecfa.unige.ch/MALTT-NOTES</app-url>
	</app-info>
	<pages>
		<page>
			<page-title>Homepage</page-title>
			<page-href>/index.html</page-href>
			<page-description>Page d'acculeil de l'application</page-description>
			<model>
				<processes>
					<process>
						<process-description>Check du login et redirection à la page personnelle</process-description>
					</process>
				</processes>
				<variables>
					<var>
						<var-name>loginFailedMessage</var-name>
						<var-type>String</var-type>
						<var-content>Message d'erreur si le login n'est pas correct</var-content>
					</var>
				</variables>
			</model>
			<view>
				<layout-description>Page d'accueil avec brève description de l'utilité du site et formulaire de login pour accéder à la page personnelle.</layout-description>
				<sketch>sketches/home.png</sketch>
				<components-list>
					<component-name>Header</component-name>
				</components-list>
			</view>
			<controller>
				<actions>
					<action>Saisir le formulaire de login</action>
					<action>Envoyer le formulaire de login</action>
				</actions>
			</controller>
		</page>
		<page>
			<page-title>Page personnelle</page-title>
			<page-href>/{username}/index.html</page-href>
			<page-description>Page qui s'affiche une fois que l'utilisateur a fait le login et qui présente les notes attribuées dans les deux dernières semaines.</page-description>
			<model>
				<processes>
					<process>
						<process-description>Récuperer toutes les notes (finales ou intermédiaires) attribuées dans les deux dernières semaines.</process-description>
					</process>
				</processes>
				<variables>
					<var>
						<var-name>lastNotes</var-name>
						<var-type>Array</var-type>
						<var-content>Date, Cours, Type, Note, Feedback</var-content>
					</var>
				</variables>
			</model>
			<view>
				<layout-description>Présentation dans un tableau des notes des derniers semaines.</layout-description>
				<sketch>sketches/mes-notes.png</sketch>
				<components-list>
					<component-name>Header</component-name>
					<component-name>Menu</component-name>
				</components-list>
			</view>
			<controller>
				<actions>
					<action>Si un feedback pour la note est disponible, cliquer sur une icône pour le lire dans une fenêtre modale.</action>
				</actions>
			</controller>
		</page>
		<page>
			<page-title>Notes finales</page-title>
			<page-href>/{username}/finales.html</page-href>
			<page-description>Affichage des notes finales des cours en fonction des périodes.</page-description>
			<model>
				<processes>
					<process>
						<process-description>Recuperer les sessions d'examens aux quelles l'étudiant a été inscrit.</process-description>
					</process>
					<process>
						<process-description>Recuperer les notes pour chaque session.</process-description>
					</process>
				</processes>
				<variables>
					<var>
						<var-name>periodes</var-name>
						<var-type>Array</var-type>
						<var-content>Semestre, Année</var-content>
					</var>
					<var>
						<var-name>notes</var-name>
						<var-type>Array</var-type>
						<var-content>Semestre, Année, Cours, Credits, Note, Feedback</var-content>
					</var>
				</variables>
			</model>
			<view>
				<layout-description>Afficher les notes finales dans un tableau</layout-description>
				<components-list>
					<component-name>Header</component-name>
					<component-name>Menu</component-name>
				</components-list>
			</view>
			<controller>
				<actions>
					<action>Si un feedback pour la note est disponible, cliquer sur une icône pour le lire dans une fenêtre modale.</action>
					<action>Si le cours présente des notes intermédiaire, cliquer sur une icône pour afficher les détails dans une fenêtre modale</action>
					<action>Imprimer la liste des notes finales</action>
				</actions>
			</controller>
		</page>
		<page>
			<page-title>Toutes les notes</page-title>
			<page-href>/{username}/toutes.html</page-href>
			<page-description>Affichage de toutes les notes attribués à l'étudiant avec des filtres pour restreindre les résultats.</page-description>
			<model>
				<processes>
					<process>
						<process-description>Recuperer les notes selon la composition de différents filtres (Semestre, Année, Cours, Type de note)</process-description></process>
				</processes>
				<variables>
					<var>
						<var-name>notes</var-name>
						<var-type>Array</var-type>
						<var-content>Semestre, Année, Cours, Type, Note, Feedback</var-content>
					</var>
					<var>
						<var-name>semesters</var-name>
						<var-type>Array</var-type>
						<var-content>Liste des semestres</var-content>
					</var>
					<var>
						<var-name>years</var-name>
						<var-type>Array</var-type>
						<var-content>Liste des années accadémiques</var-content>
					</var>
					<var>
						<var-name>courses</var-name>
						<var-type>Array</var-type>
						<var-content>Liste des cours universitaires</var-content>
					</var>
					<var>
						<var-name>types</var-name>
						<var-type>Boolean</var-type>
						<var-content>0 pour note intermédiaire et 1 pour note finale</var-content>
					</var>
				</variables>
			</model>
			<view>
				<layout-description>Liste des notes dans un tableau avec formulaire de recherche pour affiner les résultats</layout-description>
				<components-list>
					<component-name>Header</component-name>
					<component-name>Menu</component-name>
				</components-list>
			</view>
			<controller>
				<actions>
					<action>Choisir le type de semestre</action>
					<action>Choisir l'année académique</action>
					<action>Choisir le cours</action>
					<action>Choisir le type de note (final ou intermédiaire)</action>
					<action>Si un feedback pour la note est disponible, cliquer sur une icône pour le lire dans une fenêtre modale.</action>
				</actions>
			</controller>
		</page>
	</pages>
	<components>
		<component>
			<component-name>Header</component-name>
			<component-description>Entête générale</component-description>
			<model>
				<processes>
					<process>
						<process-description>Contrôle si l'utilisateur a fait le login pour montrer ou pas le lien de logout</process-description>
					</process>
				</processes>
				<variables>
					<var>
						<var-name>isLoogedIn</var-name>
						<var-type>Boolean</var-type>
						<var-content>Vrai ou fausse selon que l'utilisateur ait fait ou pas le login</var-content>
					</var>
				</variables>
			</model>
			<view>
				<layout-description>Logo de l'application, titre et éventuel lien de logout</layout-description>
			</view>
			<controller>
				<actions>
					<action>Aucune action disponible</action>
				</actions>
			</controller>
		</component>
		<component>
			<component-name>Menu</component-name>
			<component-description>Menu principale pour utiliser l'application</component-description>
			<model>
				<processes>
					<process>
						<process-description>Contrôle de la page actuelle pour mettre en évidence le  lien correpondant dans les entrées du menu</process-description>
					</process>
				</processes>
				<variables>
					<var>
						<var-name>currentUrl</var-name>
						<var-type>String</var-type>
						<var-content>URL de la page currente</var-content>
					</var>
				</variables>
			</model>
			<view>
				<layout-description>Liste des liens principales de l'application organisés verticalement</layout-description>
			</view>
			<controller>
				<actions>
					<action>Choisir un lien du menu principale</action>
				</actions>
			</controller>
		</component>
	</components>
</web-app>
