=== MALTT-STIC/stic-2-xml-dtd-xslt/tasks/03-instruction-for-objective/instr-obj.dtd
<!--
    We define a simple DTD that indicates an objective and the instructions to reach it.
    The instruction can be either ordered (sequence) or unordered (list)
-->

<!-- We define a root objective that can contain one or more single objective -->
<!ELEMENT objectives (objective+)>

<!-- The objective contains a title, a description and either a sequence or a list -->
<!ELEMENT objective (title, description, (sequence | list))>

<!-- The title contains only text -->
<!ELEMENT title (#PCDATA)>

<!-- The description contains only text -->
<!ELEMENT description (#PCDATA)>

<!-- A sequence contains one or more instructions -->
<!ELEMENT sequence (instruction+)>

<!-- Also a list contains one more more instructions -->
<!ELEMENT list (instruction+)>

<!-- We must define the instruction element, NOTE THAT IT MUST BE DEFINED ONLY ONCE -->
<!ELEMENT instruction (#PCDATA)>

=== MALTT-STIC/stic-2-xml-dtd-xslt/tasks/03-instruction-for-objective/instr-obj.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE objectives SYSTEM "instr-obj.dtd">

<?xml-stylesheet type="text/xsl" href="instr-obj.xsl"?>

<objectives>
    <objective>
        <title>An objective</title>
        <description>Something that must be done in steps</description>
        <sequence>
            <instruction>First thing to do</instruction>
            <instruction>Second thing to do</instruction>
            <instruction>...</instruction>
        </sequence>
    </objective>

    <objective>
        <title>Another objective</title>
        <description>Something that can be done without order</description>
        <list>
            <instruction>This must be done</instruction>
            <instruction>This must also be done</instruction>
            <instruction>...</instruction>
        </list>
    </objective>

</objectives>
